name: digimidi-query-builder
services:
  - name: digimidi-query-builder
    type: web
    image: digimidi-query-builder:latest
    ports:
      - port: 3000
        protocol: http
    healthcheck:
      path: /health
      port: 3000
      interval: 30s
      timeout: 10s
      retries: 3
    env:
      - name: NODE_ENV
        value: production
      - name: PORT
        value: "3000"
    resources:
      cpu: 0.1
      memory: 256Mi
    scaling:
      min_instances: 1
      max_instances: 3
    regions:
      - fra
